/* Page copy for the interactive pages (home, shop, configurator, admin, 404), in both languages.
   The long prose pages (about, privacy, terms, refunds, cookies) stay as HTML fragments in src/content/<lang>/*.html. */
import type { Lang } from './lib/kit';

const en = {
  home: {
    eyebrow: 'Vinyl door kits for the Citroën Ami',
    h1: ['Small car.', 'Big', 'personality.'],
    lead: 'Pre-cut sticker kits for the lower door panel and rear quarter window of your Ami. Pick a design, set two colours and see it on your car before you order.',
    open: 'Open configurator', browse: 'Browse designs', showDesign: 'Show design',
    specs: [['Material', 'Outdoor vinyl'], ['Finish', 'Matte or gloss'], ['Shape', 'Pre-cut'], ['Fitting', 'At home']],
    popular: 'Popular designs', all: (n: number) => `All ${n} designs`,
    how: 'How it works',
    steps: [['Pick a design', 'Choose from fifteen designs, then set a primary and an accent vinyl colour.'], ['Preview it', 'Zoom in on the door panel and rear window, and compare matte with gloss.'], ['Apply at home', 'Panels arrive pre-cut, with a step-by-step fitting guide for doing it yourself.']],
    fitEyebrow: 'Fitment', fitTitle: 'Cut for the Citroën Ami',
    fitText: 'Every kit covers two areas: the rounded panel around the door badge and the rear quarter window. The roof stays black, and nothing goes over seals or hinges.',
    fitList: [['Citroën Ami', '2020 →'], ['Finish', 'matte or gloss'], ['Sides', 'one or both'], ['Kit contents', 'door panel + rear window']],
    canvas: "More than a car. It's your canvas.", designYours: 'Design yours',
    versionsEyebrow: 'Configurator', versionsTitle: 'Choose your version',
    versions: [['qs', 'Ami QuickSilver', 'The original Ami, with grey door panels ready for a kit.'], ['pop', 'Ami Pop', 'The sporty Ami with spoiler and orange details.']] as [string, string, string][],
    from: (p: string) => `From ${p}`, configure: 'Configure',
  },
  shop: {
    eyebrow: 'Shop', h1: 'All designs', designs: 'Designs', filter: 'Filter by category',
    lead: 'Each kit covers the lower door panel and the rear quarter window. Prices are for one side; add the second side in the configurator.',
  },
  cfg: {
    options: 'Options', back: 'Back to models', h1: ['Customize', 'your Ami'],
    lead: 'Choose a design, adjust the colours and see your Ami change in real time.',
    version: 'Ami version', design: 'Design', browse: 'Browse', browseAria: 'Browse designs', colours: 'Vinyl colours',
    fixed: 'This artwork is printed in its own colours.', finishKit: 'Finish & kit', finish: 'Finish', matte: 'Matte', gloss: 'Gloss',
    kitSize: 'Kit size', one: 'One side', both: (p: string) => `Both +${p}`,
    badge: 'Badge text', badgeHint: (p: string) => `Your text on the door badge, +${p}`, badgePh: 'Up to 8 characters',
    preview: 'Preview', prev: 'Previous design', next: 'Next design', replay: 'Replay drive-in', camera: 'Camera view',
    views: [['full', 'Full car'], ['door', 'Door'], ['window', 'Rear window']] as [string, string][], hint: '← → to switch designs',
    kicker: ['Small car.', 'Big personality.'], tagline: 'Same Ami. Different vibe.', yourKit: 'Your kit', total: 'Total',
    persBefore: "Personalised kit: made to your choices, so it can't be ", persLink: 'returned', persAfter: ' for a change of mind. Faulty kits are always covered.',
    ship: ['Made to order', 'Shipping and delivery times shown at checkout'],
    specs: [['Vinyl', 'Outdoor vinyl, matte or gloss'], ['Panels', 'Door panel + rear window, per side'], ['Includes', 'Step-by-step fitting guide']],
    summaryBtn: 'Summary', summaryTitle: 'Your kit summary', selection: 'Your selection', change: 'Change', changeAria: (x: string) => `Change ${x}`,
    zoomIn: 'Zoom in', zoomOut: 'Zoom out', fullscreen: 'Full screen', dragHint: 'Drag to look around',
    scenery: 'Scenery', studio: 'Studio', beach: 'Beach',
    brochure: {
      eyebrow: 'The kit', title: 'Made for the Ami, down to the millimetre.',
      lead: 'Every OFS/T kit is cut to the shapes of the Ami door panel and rear window, printed on outdoor vinyl and packed with everything you need to fit it at home.',
      cards: [
        ['Outdoor vinyl', 'Weather- and UV-resistant cast vinyl in a matte or gloss finish.'],
        ['Cut to fit', 'Panels follow the factory sticker areas of the Ami, so the lines sit where they should.'],
        ['Fit it yourself', 'A step-by-step guide and squeegee method, no tools beyond a spray bottle.'],
        ['Made to order', 'Printed for your car in your colours once you order.'],
      ] as [string, string][],
    },
    choose: 'Choose a design', designsGroup: 'Designs',
  },
  notFound: { eyebrow: 'Error 404', h1: 'Page not found', text: "That page doesn't exist or has moved. Try the shop, or design your own kit in the configurator.", browse: 'Browse designs', home: 'Back to home', other: null as null | [string, string] },
  admin: {
    eyebrow: 'Admin', h1: 'Orders', lead: "Every door kit is laid out on the print mold with the customer's colours. Download a PNG (transparent, 6000 px wide) or an SVG with a magenta CutContour layer.",
    loading: 'Loading…', setupTitle: "Online ordering isn't set up yet", setupIntro: 'Orders are stored in a free Cloudflare D1 database that only you can read. To switch it on:',
    steps: [
      'In <code>worker/</code>, log in with <code>npx wrangler login</code> and create the database: <code>npx wrangler d1 create ofst-orders</code>. Paste the <code>database_id</code> into <code>worker/wrangler.jsonc</code>.',
      'Create the tables: <code>npm run db:remote</code> (inside <code>worker/</code>).',
      'Set your admin sign-in: <code>npx wrangler secret put ADMIN_EMAIL</code> and <code>npx wrangler secret put ADMIN_PASSWORD</code> (12+ characters).',
      'Put your website address in <code>ALLOWED_ORIGINS</code> in <code>worker/wrangler.jsonc</code>, then publish the API with <code>npm run deploy</code>.',
      'Copy the Worker address it prints (https://ofst-api….workers.dev) into <code>src/data/site.json</code> as <code>apiUrl</code>. Never put a password in that file.',
      'Run <code>npm run build</code>, then commit and push.',
    ],
    setupNote: 'The full walkthrough is in <code>guides/CLOUDFLARE-SETUP.md</code>. The print-file tool below works without a database.',
    signIn: 'Sign in', email: 'Email', password: 'Password',
    lockedTitle: "This account isn't an admin", lockedText: 'You are signed in, but this account is not listed in the <code>admins</code> table, so no orders are shown.', signOut: 'Sign out',
    listTitle: 'Order list', refresh: 'Refresh',
    toolTitle: 'Mold file of a design', toolNote: "A test print file in the design's default colours, to check the printer setup.", design: 'Design', png: 'Download PNG', svg: 'SVG + cut line',
  },
};

const pt: typeof en = {
  home: {
    eyebrow: 'Kits de vinil para as portas do Citroën Ami',
    h1: ['Carro pequeno.', 'Grande', 'personalidade.'],
    lead: 'Kits de autocolantes pré-cortados para o painel inferior da porta e o vidro lateral traseiro do seu Ami. Escolha um design, defina duas cores e veja o resultado no seu carro antes de encomendar.',
    open: 'Abrir configurador', browse: 'Ver designs', showDesign: 'Mostrar design',
    specs: [['Material', 'Vinil de exterior'], ['Acabamento', 'Mate ou brilhante'], ['Formato', 'Pré-cortado'], ['Aplicação', 'Em casa']],
    popular: 'Designs populares', all: (n: number) => `Todos os ${n} designs`,
    how: 'Como funciona',
    steps: [['Escolha um design', 'Escolha entre quinze designs e defina uma cor de vinil principal e uma cor de destaque.'], ['Pré-visualize', 'Aproxime a vista do painel da porta e do vidro traseiro e compare o acabamento mate com o brilhante.'], ['Aplique em casa', 'Os painéis chegam pré-cortados, com um guia de aplicação passo a passo para fazer tudo por conta própria.']],
    fitEyebrow: 'Compatibilidade', fitTitle: 'Cortado para o Citroën Ami',
    fitText: 'Cada kit cobre duas zonas: o painel arredondado à volta do emblema da porta e o vidro lateral traseiro. O tejadilho fica preto e nada é aplicado sobre borrachas ou dobradiças.',
    fitList: [['Citroën Ami', '2020 →'], ['Acabamento', 'mate ou brilhante'], ['Lados', 'um ou os dois'], ['Conteúdo do kit', 'painel da porta + vidro traseiro']],
    canvas: 'Mais do que um carro. É a sua tela.', designYours: 'Crie o seu',
    versionsEyebrow: 'Configurador', versionsTitle: 'Escolhe a tua versão',
    versions: [['qs', 'Ami QuickSilver', 'O Ami original, com os painéis das portas cinzentos prontos para um kit.'], ['pop', 'Ami Pop', 'O Ami desportivo, com spoiler e detalhes laranja.']] as [string, string, string][],
    from: (p: string) => `Desde ${p}`, configure: 'Configurar',
  },
  shop: {
    eyebrow: 'Loja', h1: 'Todos os designs', designs: 'Designs', filter: 'Filtrar por categoria',
    lead: 'Cada kit cobre o painel inferior da porta e o vidro lateral traseiro. Os preços são por lado; acrescente o segundo lado no configurador.',
  },
  cfg: {
    options: 'Opções', back: 'Voltar aos modelos', h1: ['Personalize', 'o seu Ami'],
    lead: 'Escolha um design, ajuste as cores e veja o seu Ami mudar em tempo real.',
    version: 'Versão do Ami', design: 'Design', browse: 'Explorar', browseAria: 'Explorar designs', colours: 'Cores do vinil',
    fixed: 'Esta arte é impressa nas suas próprias cores.', finishKit: 'Acabamento e kit', finish: 'Acabamento', matte: 'Mate', gloss: 'Brilhante',
    kitSize: 'Tamanho do kit', one: 'Um lado', both: (p: string) => `Os dois +${p}`,
    badge: 'Texto do emblema', badgeHint: (p: string) => `O seu texto no emblema da porta, +${p}`, badgePh: 'Até 8 caracteres',
    preview: 'Pré-visualização', prev: 'Design anterior', next: 'Design seguinte', replay: 'Repetir a entrada do carro', camera: 'Vista da câmara',
    views: [['full', 'Carro inteiro'], ['door', 'Porta'], ['window', 'Vidro traseiro']] as [string, string][], hint: '← → para mudar de design',
    kicker: ['Carro pequeno.', 'Grande personalidade.'], tagline: 'O mesmo Ami. Outra atitude.', yourKit: 'O seu kit', total: 'Total',
    persBefore: 'Kit personalizado: é feito de acordo com as suas escolhas, por isso não pode ser ', persLink: 'devolvido', persAfter: ' por mudança de opinião. Os kits com defeito estão sempre cobertos.',
    ship: ['Feito por encomenda', 'Portes e prazos de entrega indicados ao finalizar a compra'],
    specs: [['Vinil', 'Vinil de exterior, mate ou brilhante'], ['Painéis', 'Painel da porta + vidro traseiro, por lado'], ['Inclui', 'Guia de aplicação passo a passo']],
    summaryBtn: 'Resumo', summaryTitle: 'Resumo do seu kit', selection: 'A sua seleção', change: 'Alterar', changeAria: (x: string) => `Alterar ${x}`,
    zoomIn: 'Aproximar', zoomOut: 'Afastar', fullscreen: 'Ecrã inteiro', dragHint: 'Arraste para explorar',
    scenery: 'Cenário', studio: 'Estúdio', beach: 'Praia',
    brochure: {
      eyebrow: 'O kit', title: 'Feito para o Ami, ao milímetro.',
      lead: 'Cada kit OFS/T é cortado à medida do painel da porta e do vidro traseiro do Ami, impresso em vinil de exterior e enviado com tudo o que precisa para o aplicar em casa.',
      cards: [
        ['Vinil de exterior', 'Vinil fundido resistente ao tempo e aos raios UV, em acabamento mate ou brilhante.'],
        ['Cortado à medida', 'Os painéis seguem as zonas de autocolante de origem do Ami, para as linhas ficarem no sítio certo.'],
        ['Aplique você mesmo', 'Um guia passo a passo e o método da espátula, só precisa de um pulverizador.'],
        ['Feito por encomenda', 'Impresso para o seu carro, nas suas cores, depois de encomendar.'],
      ] as [string, string][],
    },
    choose: 'Escolha um design', designsGroup: 'Designs',
  },
  notFound: { eyebrow: 'Erro 404', h1: 'Página não encontrada', text: 'Esta página não existe ou mudou de endereço. Experimente a loja ou crie o seu próprio kit no configurador.', browse: 'Ver designs', home: 'Voltar ao início', other: ["Page not found: this page doesn't exist or has moved.", 'Go to the English site'] },
  admin: {
    eyebrow: 'Administração', h1: 'Encomendas', lead: 'Cada kit de porta é colocado no molde de impressão com as cores escolhidas pelo cliente. Descarregue um PNG (transparente, 6000 px de largura) ou um SVG com uma camada CutContour a magenta.',
    loading: 'A carregar…', setupTitle: 'As encomendas online ainda não estão ativas', setupIntro: 'As encomendas ficam guardadas numa base de dados gratuita Cloudflare D1 que só o proprietário pode ler. Para a ativar:',
    steps: [
      'Em <code>worker/</code>, inicie sessão com <code>npx wrangler login</code> e crie a base de dados: <code>npx wrangler d1 create ofst-orders</code>. Cole o <code>database_id</code> em <code>worker/wrangler.jsonc</code>.',
      'Crie as tabelas: <code>npm run db:remote</code> (dentro de <code>worker/</code>).',
      'Defina o seu acesso de administrador: <code>npx wrangler secret put ADMIN_EMAIL</code> e <code>npx wrangler secret put ADMIN_PASSWORD</code> (12+ caracteres).',
      'Coloque o endereço do seu site em <code>ALLOWED_ORIGINS</code> em <code>worker/wrangler.jsonc</code> e publique a API com <code>npm run deploy</code>.',
      'Copie o endereço do Worker que aparece (https://ofst-api….workers.dev) para <code>src/data/site.json</code> como <code>apiUrl</code>. Nunca coloque uma palavra-passe nesse ficheiro.',
      'Execute <code>npm run build</code> e depois faça commit e push.',
    ],
    setupNote: 'O guia completo está em <code>guides/CLOUDFLARE-SETUP.md</code>. A ferramenta de ficheiros de impressão abaixo funciona sem base de dados.',
    signIn: 'Iniciar sessão', email: 'Email', password: 'Palavra-passe',
    lockedTitle: 'Esta conta não é de administrador', lockedText: 'Tem sessão iniciada, mas esta conta não consta da tabela <code>admins</code>, por isso não são apresentadas encomendas.', signOut: 'Terminar sessão',
    listTitle: 'Lista de encomendas', refresh: 'Atualizar',
    toolTitle: 'Ficheiro de molde de um design', toolNote: 'Um ficheiro de impressão de teste nas cores predefinidas do design, para verificar a configuração da impressora.', design: 'Design', png: 'Descarregar PNG', svg: 'SVG + linha de corte',
  },
};

export const COPY: Record<Lang, typeof en> = { en, pt };
