/* Interface text for the dashboard tabs (pt-PT + English). Plain text only, rendered by React as text. */
const en = {
  tabs: { overview: 'Overview', reports: 'Sales reports', orders: 'Orders', invoices: 'Invoices', customers: 'Customers', tools: 'Print tools' },
  tabsLabel: 'Dashboard sections',
  range: 'Period', ranges: { today: 'Today', '7': '7 days', '30': '30 days', '90': '90 days', all: 'All time' },
  vsPrev: 'vs previous period',
  k: { revenue: 'Revenue', orders: 'Orders', aov: 'Avg. order', units: 'Stickers sold', toPrint: 'To print', issues: 'Payment issues', customers: 'Customers' },
  kHint: { revenue: 'Paid through Stripe', issues: 'Amount differs from order: check in Stripe', toPrint: 'All time, status New' },
  trendTitle: 'Revenue over time', trendOrders: 'Orders over time', metric: 'Show', mRevenue: 'Revenue', mOrders: 'Orders',
  noData: 'No sales in this period yet.', ordersN: (n: number) => (n === 1 ? '1 order' : `${n} orders`),
  showTable: 'Show as table', date: 'Date', recent: 'Latest orders', seeAll: 'See all orders',
  statusMix: 'Fulfilment', payMix: 'Payment',
  topDesigns: 'Top designs', topDesignsNote: 'Kits sold · revenue on hover',
  colours: 'Most-ordered colours', coloursNote: 'Kits using each colour (custom-colour designs)',
  kitType: 'Kit type', finish: 'Finish', model: 'Car model', badge: 'Custom number badge', badgeOf: (p: string) => `${p} of kits add a number`,
  countries: 'Countries', cities: 'Top cities', weekdays: 'Orders by weekday', hours: 'Orders by hour',
  wd: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  kits: (n: number) => (n === 1 ? '1 kit' : `${n} kits`), ordersShort: (n: number) => `${n}`,
  search: 'Search', searchPh: 'Name, email, #ref, city…', status: 'Status', payment: 'Payment', sort: 'Sort',
  all: 'All', paid: 'Paid', mismatch: 'Mismatch',
  sorts: { new: 'Newest first', old: 'Oldest first', high: 'Highest value', low: 'Lowest value' },
  showing: (a: number, b: number) => `Showing ${a} of ${b} orders`,
  mailAll: 'Email all paid orders', mailConfirm: (n: number) => `Send the confirmation email to ${n} paid ${n === 1 ? 'order' : 'orders'}?`, mailYes: 'Send', mailNo: 'Cancel',
  mailSending: 'Sending emails…', mailDone: (s: number, f: number, r: number) => `${s} sent${f ? `, ${f} failed` : ''}${r ? `. ${r} left: click again to send them.` : '.'}`,
  mailNotConfigured: 'Emails are not set up on the order server yet (RESEND_API_KEY missing).', mailFailed: 'Resend refused the emails: check the API key and that ofstdesigns.com is verified in Resend.',
  exportCsv: 'Export CSV', bulkPng: 'All print files (PNG)', bulkSvg: 'All print files (SVG)',
  bulkNote: (n: number) => (n === 1 ? '1 kit waiting to print' : `${n} kits waiting to print`), bulkNone: 'Nothing waiting to print.',
  bulkProgress: (a: number, b: number) => `Preparing file ${a} of ${b}…`, bulkDone: (n: number) => `${n} files downloaded.`,
  details: 'Print files', hideDetails: 'Hide',
  custTitle: 'Customers', repeatTag: 'Repeat', more: (n: number) => `Show ${n} more`, repeat: 'Repeat buyers', repeatOf: (p: string) => `${p} ordered more than once`,
  avgSpend: 'Avg. spend per customer', custCount: 'Customers',
  cName: 'Customer', cOrders: 'Orders', cSpent: 'Spent', cLast: 'Last order', cPlace: 'Location',
  noCustomers: 'No customers in this period.',
  invoicesTitle: 'Invoices to send', invoicesNote: 'Paid orders without an invoice. Adding a file sends it to the buyer by email.', invoiceEmpty: 'All paid orders have an invoice.', invoiceFile: 'Invoice file', invoiceItems: 'Ordered items', invoiceSend: 'Add invoice and email buyer', invoiceTypes: 'PDF, PNG or JPEG, up to 750 KB', invoicePreview: 'Preview', invoiceHidePreview: 'Hide preview', invoiceSent: 'Invoice sent to the buyer.',
  csvHead: ['Order', 'Date', 'Status', 'Payment', 'Name', 'Email', 'Street', 'Postcode', 'City', 'Country', 'Items', 'Stickers', 'Total (EUR)'],
  limitNote: 'Figures cover the newest 500 paid orders.',
};
const pt: typeof en = {
  tabs: { overview: 'Resumo', reports: 'Relatórios de vendas', orders: 'Encomendas', invoices: 'Faturas', customers: 'Clientes', tools: 'Ficheiros de impressão' },
  tabsLabel: 'Secções do painel',
  range: 'Período', ranges: { today: 'Hoje', '7': '7 dias', '30': '30 dias', '90': '90 dias', all: 'Sempre' },
  vsPrev: 'vs período anterior',
  k: { revenue: 'Receita', orders: 'Encomendas', aov: 'Valor médio', units: 'Autocolantes vendidos', toPrint: 'Por imprimir', issues: 'Problemas de pagamento', customers: 'Clientes' },
  kHint: { revenue: 'Pago via Stripe', issues: 'Valor diferente da encomenda: verifique na Stripe', toPrint: 'Total, estado Nova' },
  trendTitle: 'Receita ao longo do tempo', trendOrders: 'Encomendas ao longo do tempo', metric: 'Mostrar', mRevenue: 'Receita', mOrders: 'Encomendas',
  noData: 'Ainda sem vendas neste período.', ordersN: (n: number) => (n === 1 ? '1 encomenda' : `${n} encomendas`),
  showTable: 'Ver como tabela', date: 'Data', recent: 'Últimas encomendas', seeAll: 'Ver todas',
  statusMix: 'Produção', payMix: 'Pagamento',
  topDesigns: 'Designs mais vendidos', topDesignsNote: 'Kits vendidos · receita ao passar o rato',
  colours: 'Cores mais pedidas', coloursNote: 'Kits com cada cor (designs de cor personalizável)',
  kitType: 'Tipo de kit', finish: 'Acabamento', model: 'Modelo', badge: 'Número personalizado', badgeOf: (p: string) => `${p} dos kits têm número`,
  countries: 'Países', cities: 'Principais cidades', weekdays: 'Encomendas por dia da semana', hours: 'Encomendas por hora',
  wd: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
  kits: (n: number) => (n === 1 ? '1 kit' : `${n} kits`), ordersShort: (n: number) => `${n}`,
  search: 'Pesquisar', searchPh: 'Nome, email, #ref, cidade…', status: 'Estado', payment: 'Pagamento', sort: 'Ordenar',
  all: 'Todos', paid: 'Pago', mismatch: 'Divergente',
  sorts: { new: 'Mais recentes', old: 'Mais antigas', high: 'Maior valor', low: 'Menor valor' },
  showing: (a: number, b: number) => `A mostrar ${a} de ${b} encomendas`,
  mailAll: 'Enviar email às pagas', mailConfirm: (n: number) => `Enviar o email de confirmação a ${n} ${n === 1 ? 'encomenda paga' : 'encomendas pagas'}?`, mailYes: 'Enviar', mailNo: 'Cancelar',
  mailSending: 'A enviar emails…', mailDone: (s: number, f: number, r: number) => `${s} ${s === 1 ? 'enviado' : 'enviados'}${f ? `, ${f} falharam` : ''}${r ? `. Faltam ${r}: clique outra vez para os enviar.` : '.'}`,
  mailNotConfigured: 'Os emails ainda não estão configurados no servidor (falta o RESEND_API_KEY).', mailFailed: 'A Resend recusou os emails: verifique a chave API e se o domínio ofstdesigns.com está verificado na Resend.',
  exportCsv: 'Exportar CSV', bulkPng: 'Todos os ficheiros (PNG)', bulkSvg: 'Todos os ficheiros (SVG)',
  bulkNote: (n: number) => (n === 1 ? '1 kit por imprimir' : `${n} kits por imprimir`), bulkNone: 'Nada por imprimir.',
  bulkProgress: (a: number, b: number) => `A preparar ficheiro ${a} de ${b}…`, bulkDone: (n: number) => `${n} ficheiros transferidos.`,
  details: 'Ficheiros de impressão', hideDetails: 'Ocultar',
  custTitle: 'Clientes', repeatTag: 'Recorrente', more: (n: number) => `Mostrar mais ${n}`, repeat: 'Clientes recorrentes', repeatOf: (p: string) => `${p} encomendaram mais de uma vez`,
  avgSpend: 'Gasto médio por cliente', custCount: 'Clientes',
  cName: 'Cliente', cOrders: 'Encomendas', cSpent: 'Gasto', cLast: 'Última encomenda', cPlace: 'Localização',
  noCustomers: 'Sem clientes neste período.',
  invoicesTitle: 'Faturas por enviar', invoicesNote: 'Encomendas pagas sem fatura. Ao adicionar um ficheiro, este é enviado por email ao comprador.', invoiceEmpty: 'Todas as encomendas pagas têm fatura.', invoiceFile: 'Ficheiro da fatura', invoiceItems: 'Artigos pedidos', invoiceSend: 'Adicionar fatura e enviar email', invoiceTypes: 'PDF, PNG ou JPEG, até 750 KB', invoicePreview: 'Pré-visualizar', invoiceHidePreview: 'Fechar pré-visualização', invoiceSent: 'Fatura enviada ao comprador.',
  csvHead: ['Encomenda', 'Data', 'Estado', 'Pagamento', 'Nome', 'Email', 'Morada', 'Código postal', 'Cidade', 'País', 'Artigos', 'Autocolantes', 'Total (EUR)'],
  limitNote: 'Os valores incluem as 500 encomendas pagas mais recentes.',
};
export const DASH = { en, pt };
export type DashCopy = typeof en;
